### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by ethanmick** [jaredraby/bubblesort#2]
Add GitHub's Gitignore to every project you do:

https://github.com/github/gitignore/blob/master/Python.gitignore

Remove .pyc files from the repo, they are compiled artifacts.

**Comment by jaredraby** [comment]
Added the python.gitignore to the project repo

**Comment by ethanmick** [comment]
You need to still remove the `bubblesort.pyc` from the project. Adding the gitignore doesn't remove it, since it was previously added to the repo.

**Comment by jaredraby** [comment]
Removed `bubblesort.pyc` from the repo and tracking in git. 

Commit: a62ae57899b12c6c099d9993afd670d5ff850327
